# Generated by Django 4.2 on 2023-12-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userletter',
            name='email',
        ),
        migrations.AddField(
            model_name='userletter',
            name='phone',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
