# Generated by Django 4.2 on 2023-12-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_userletter_email_userletter_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='body',
            field=models.CharField(max_length=350),
        ),
    ]
